# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rails-patterns 0.11.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rails-patterns".freeze
  s.version = "0.11.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Stevo".freeze]
  s.date = "2022-02-09"
  s.description = "A collection of lightweight, standardized, rails-oriented patterns.".freeze
  s.email = "b.kosmowski@selleo.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".github/workflows/ruby.yml",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/patterns.rb",
    "lib/patterns/calculation.rb",
    "lib/patterns/collection.rb",
    "lib/patterns/form.rb",
    "lib/patterns/query.rb",
    "lib/patterns/rule.rb",
    "lib/patterns/ruleset.rb",
    "lib/patterns/service.rb",
    "lib/patterns/strong_ruleset.rb",
    "lib/rails-patterns.rb",
    "rails-patterns.gemspec",
    "spec/helpers/custom_calculation.rb",
    "spec/helpers/custom_calculation_script.rb",
    "spec/helpers/rails_redis_cache_mock.rb",
    "spec/patterns/calculation_spec.rb",
    "spec/patterns/collection_spec.rb",
    "spec/patterns/form_spec.rb",
    "spec/patterns/query_spec.rb",
    "spec/patterns/rule_spec.rb",
    "spec/patterns/ruleset_spec.rb",
    "spec/patterns/service_spec.rb",
    "spec/patterns/strong_ruleset_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/selleo/pattern".freeze
  s.licenses = ["MIT".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 2.5.0".freeze)
  s.rubygems_version = "3.0.8".freeze
  s.summary = "A collection of lightweight, standardized, rails-oriented patterns.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>.freeze, [">= 4.2.6"])
      s.add_runtime_dependency(%q<actionpack>.freeze, [">= 4.2.6"])
      s.add_runtime_dependency(%q<virtus>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<ruby2_keywords>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 2.0"])
      s.add_development_dependency(%q<juwelier>.freeze, [">= 0"])
    else
      s.add_dependency(%q<activerecord>.freeze, [">= 4.2.6"])
      s.add_dependency(%q<actionpack>.freeze, [">= 4.2.6"])
      s.add_dependency(%q<virtus>.freeze, [">= 0"])
      s.add_dependency(%q<ruby2_keywords>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_dependency(%q<bundler>.freeze, ["~> 2.0"])
      s.add_dependency(%q<juwelier>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>.freeze, [">= 4.2.6"])
    s.add_dependency(%q<actionpack>.freeze, [">= 4.2.6"])
    s.add_dependency(%q<virtus>.freeze, [">= 0"])
    s.add_dependency(%q<ruby2_keywords>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
    s.add_dependency(%q<bundler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<juwelier>.freeze, [">= 0"])
  end
end

